version: '3'
services:
    web:
        build: ./app
        container_name: krilljs-flask
        ports:
           - 5016:5000
        volumes:
           - ./app/data:/data
    redis:
        image: redis:latest
        container_name: krilljs-redis
        ports:
            - 6396:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
