---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: krilljs-final-prod-redis-pvc
  labels:
    username: krilljs
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
