apiVersion: v1
kind: Service
metadata:
  name: krilljs-final-prod-redis-service
  labels:
    username: krilljs
    env: prod
spec:
  type: ClusterIP
    clusterIP: 0.0.0.0
  selector:
    username: krilljs
    env: prod
    app: krilljs-final-prod-redis
  ports:
  - name: krilljs-final-prod-redis
    port: 6379
    targetPort: 6379
