---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krilljs-final-prod-flask-deployment
  labels:
    username: krilljs
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      username: krilljs
      env: prod
  template:
    metadata:
      labels:
        username: krilljs
        env: prod
        app: krilljs-final-prod-flask
    spec:
      containers:
        - name: test
          imagePullPolicy: Always
          image: jeremykrill/final-project-app:1.0
          args: ["api.py"]
          env:
          - name: FLASK_APP
            value: "api.py"
          - name: FLASK_ENV
            value: "development"
          - name: REDIS_IP
            value: "0.0.0.0" # Change this to the Cluster IP of the redis service
          ports:
          - name: http
            containerPort: 5000
