---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krilljs-final-prod-worker-deployment
  labels:
    username: krilljs
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      username: krilljs
      env: prod
  template:
    metadata:
      labels:
        username: krilljs
        env: prod
        app: krilljs-prod-worker
    spec:
      containers:
        - name: test
          imagePullPolicy: Always
          image: jeremykrill/final-project-app:1.0
          args: ["worker.py"]
          env:
          - name: REDIS_IP
            value: "0.0.0.0" # Change this to the Cluster IP of the redis service
          - name: PYTHONUNBUFFERED
            value: "0"
          - name: WORKER_IP
            valueFrom:
                fieldRef:
                  fieldPath: status.podIP
