apiVersion: v1
kind: Service
metadata:
    name: krilljs-test-flask
spec:
    type: ClusterIP
    selector:
        app: krilljs-test-flask
    ports: 
    - name: krilljs-test-flask-service
      port: 5000
      targetPort: 5000
