apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: krilljs-test-redis-pvc-data
    labels:
        username: krilljs
        env: test
spec:
    accessModes:
      - ReadWriteOnce
    storageClassName: rbd
    resources:
        requests:
            storage: 1Gi
