apiVersion: v1
kind: Service
metadata:
    name: krilljs-test-redis-service
    labels:
        username: krilljs
        env: test
spec:
    type: ClusterIP
    selector:
        app: krilljs-test-redis
    ports:
    - name: krilljs-test-redis-service
      port: 6379
      targetPort: 6379
