---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hw5
  labels:
    app: hw5-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw5-app
  template:
    metadata:
      labels:
        app: hw5-app
    spec:
      containers:
        - name: deployment-pod2-hw5
          image: ubuntu:18.04
          env:
            - name: "NAME"
              value: "Jeremy"
            - name: "POD_IP"
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ['sh', '-c', 'echo "Hello, $NAME from IP $POD_IP" && sleep 3600']
